import json
import os

from dotenv import load_dotenv
from sqlalchemy import create_engine, text

def load_match_participants(input_folder):
    rows =[]
    #TABLE INSERTION
    load_dotenv()
    # env vars
    user = os.getenv("POSTGRES_USER")
    password = os.getenv("POSTGRES_PASSWORD")
    database = os.getenv("POSTGRES_DB")

    database_url = (f"postgresql+psycopg://{user}:{password}@localhost:5432/{database}")
    engine = create_engine(database_url)    

    #SQL command to insert everything
    insert_query = text("""
        INSERT INTO player_matches_bronze (
        match_id ,
        game_creation_timestamp,
        game_start_timestamp ,
        game_end_timestamp ,
        game_version,
        puuid  ,
        participant_id,
        team_id ,
        summoner_id ,
        summoner_name ,
        summoner_level ,
        profile_icon ,
        riot_id_game_name ,
        riot_id_tagline,
        time_played ,
        longest_time_spent_living,
        total_time_spent_dead ,
        champion_id ,
        champion_name ,
        champion_transform ,
        champ_level ,
        champ_experience ,
        individual_position ,
        team_position ,
        lane ,
        role ,
        position_assigned_by_matchmaking ,
        selected_role_preferences,
        win ,
        eligible_for_progression ,
        game_ended_in_early_surrender ,
        game_ended_in_ignb_surrender ,
        game_ended_in_surrender,
        team_early_surrendered ,
        team_ignb_surrendered ,
        caused_game_end_from_ignb_surrender ,
        was_premade_with_ignb_game_end_causer ,
        was_premade_with_severe_transgressor ,
        was_severe_transgressor ,
        was_afk ,
        kills,
        deaths ,
        assists ,
        killing_sprees ,
        largest_killing_spree ,
        largest_multi_kill ,
        double_kills ,
        triple_kills ,
        quadra_kills ,
        penta_kills ,
        unreal_kills,
        first_blood_kill,
        first_blood_assist ,
        gold_earned ,
        gold_spent ,
        items_purchased ,
        consumables_purchased ,
        item_0 ,
        item_1,
        item_2 ,
        item_3 ,
        item_4 ,
        item_5 ,
        item_6 ,
        role_bound_item ,
        total_minions_killed ,
        neutral_minions_killed ,
        total_ally_jungle_minions_killed ,
        total_enemy_jungle_minions_killed ,
        total_damage_dealt ,
        total_damage_dealt_to_champions,
        physical_damage_dealt ,
        physical_damage_dealt_to_champions ,
        magic_damage_dealt,
        magic_damage_dealt_to_champions ,
        true_damage_dealt,
        true_damage_dealt_to_champions ,
        total_damage_taken,
        physical_damage_taken ,
        magic_damage_taken ,
        true_damage_taken ,
        damage_self_mitigated ,
        total_heal ,
        total_heals_on_teammates ,
        total_units_healed ,
        total_damage_shielded_on_teammates ,
        time_ccing_others ,
        total_time_cc_dealt ,
        damage_dealt_to_buildings ,
        damage_dealt_to_turrets ,
        damage_dealt_to_objectives ,
        damage_dealt_to_epic_monsters ,
        turret_kills ,
        turret_takedowns ,
        turrets_lost ,
        inhibitor_kills ,
        inhibitor_takedowns,
        inhibitors_lost ,
        nexus_kills ,
        nexus_takedowns,
        nexus_lost ,
        dragon_kills,
        baron_kills ,
        objectives_stolen ,
        objectives_stolen_assists ,
        first_tower_kill ,
        first_tower_assist,
        vision_score,
        wards_placed,
        wards_killed ,
        detector_wards_placed ,
        vision_wards_bought_in_game ,
        sight_wards_bought_in_game,
        all_in_pings,
        assist_me_pings ,
        basic_pings,
        command_pings ,
        danger_pings ,
        enemy_missing_pings ,
        enemy_vision_pings,
        get_back_pings,
        hold_pings ,
        need_vision_pings ,
        on_my_way_pings ,
        push_pings ,
        retreat_pings ,
        vision_cleared_pings,
        spell_1_casts,
        spell_2_casts,
        spell_3_casts ,
        spell_4_casts,
        summoner_1_id ,
        summoner_2_id ,
        summoner_1_casts ,
        summoner_2_casts ,
        placement ,
        subteam_placement ,
        player_subteam_id ,
        player_augment_1,
        player_augment_2 ,
        player_augment_3 ,
        player_augment_4, 
         player_augment_5,
        player_augment_6, 
        player_behavior,
        missions ,
        perks ,
        teams,
        tournament_code
        )
        VALUES (
        :match_id ,
        :game_creation_timestamp,
        :game_start_timestamp,
        :game_end_timestamp,
        :game_version,
        :puuid  ,
        :participant_id,
        :team_id ,
        :summoner_id ,
        :summoner_name ,
        :summoner_level ,
        :profile_icon ,
        :riot_id_game_name ,
        :riot_id_tagline,
        :time_played ,
        :longest_time_spent_living,
        :total_time_spent_dead ,
        :champion_id ,
        :champion_name ,
        :champion_transform ,
        :champ_level ,
        :champ_experience ,
        :individual_position ,
        :team_position ,
        :lane ,
        :role ,
        :position_assigned_by_matchmaking ,
        :selected_role_preferences,
        :win ,
        :eligible_for_progression ,
        :game_ended_in_early_surrender ,
        :game_ended_in_ignb_surrender ,
        :game_ended_in_surrender,
        :team_early_surrendered ,
        :team_ignb_surrendered ,
        :caused_game_end_from_ignb_surrender ,
        :was_premade_with_ignb_game_end_causer ,
        :was_premade_with_severe_transgressor ,
        :was_severe_transgressor ,
        :was_afk ,
        :kills,
        :deaths ,
        :assists ,
        :killing_sprees ,
        :largest_killing_spree ,
        :largest_multi_kill ,
        :double_kills ,
        :triple_kills ,
        :quadra_kills ,
        :penta_kills ,
        :unreal_kills,
        :first_blood_kill,
        :first_blood_assist ,
        :gold_earned ,
        :gold_spent ,
        :items_purchased ,
        :consumables_purchased ,
        :item_0 ,
        :item_1,
        :item_2 ,
        :item_3 ,
        :item_4 ,
        :item_5 ,
        :item_6 ,
        :role_bound_item ,
        :total_minions_killed ,
        :neutral_minions_killed ,
        :total_ally_jungle_minions_killed ,
        :total_enemy_jungle_minions_killed ,
        :total_damage_dealt ,
        :total_damage_dealt_to_champions,
        :physical_damage_dealt ,
        :physical_damage_dealt_to_champions ,
        :magic_damage_dealt,
        :magic_damage_dealt_to_champions ,
        :true_damage_dealt,
        :true_damage_dealt_to_champions ,
        :total_damage_taken,
        :physical_damage_taken ,
        :magic_damage_taken ,
        :true_damage_taken ,
        :damage_self_mitigated ,
        :total_heal ,
        :total_heals_on_teammates ,
        :total_units_healed ,
        :total_damage_shielded_on_teammates,
        :time_ccing_others ,
        :total_time_cc_dealt ,
        :damage_dealt_to_buildings ,
        :damage_dealt_to_turrets ,
        :damage_dealt_to_objectives ,
        :damage_dealt_to_epic_monsters ,
        :turret_kills ,
        :turret_takedowns ,
        :turrets_lost ,
        :inhibitor_kills ,
        :inhibitor_takedowns,
        :inhibitors_lost ,
        :nexus_kills ,
        :nexus_takedowns,
        :nexus_lost ,
        :dragon_kills,
        :baron_kills ,
        :objectives_stolen ,
        :objectives_stolen_assists ,
        :first_tower_kill ,
        :first_tower_assist,
        :vision_score,
        :wards_placed,
        :wards_killed ,
        :detector_wards_placed ,
        :vision_wards_bought_in_game ,
        :sight_wards_bought_in_game,
        :all_in_pings,
        :assist_me_pings ,
        :basic_pings,
        :command_pings ,
        :danger_pings ,
        :enemy_missing_pings ,
        :enemy_vision_pings,
        :get_back_pings,
        :hold_pings ,
        :need_vision_pings ,
        :on_my_way_pings ,
        :push_pings ,
        :retreat_pings ,
        :vision_cleared_pings,
        :spell_1_casts,
        :spell_2_casts,
        :spell_3_casts ,
        :spell_4_casts,
        :summoner_1_id ,
        :summoner_2_id ,
        :summoner_1_casts ,
        :summoner_2_casts ,
        :placement ,
        :subteam_placement ,
        :player_subteam_id ,
        :player_augment_1,
        :player_augment_2 ,
        :player_augment_3 ,
        :player_augment_4, 
        :player_augment_5,
        :player_augment_6, 
        CAST(:player_behavior AS JSONB),
        CAST(:missions AS JSONB),
        CAST(:perks AS JSONB),
        CAST(:teams AS JSONB),
        :tournament_code
            )
        ON CONFLICT (match_id, puuid)
        DO UPDATE SET
            game_creation_timestamp = EXCLUDED.game_creation_timestamp,
            game_start_timestamp= EXCLUDED.game_start_timestamp,
            game_end_timestamp = EXCLUDED.game_end_timestamp,
            game_version = EXCLUDED.game_version,
            participant_id = EXCLUDED.participant_id,
            team_id = EXCLUDED.team_id,
            summoner_id = EXCLUDED.summoner_id,
            summoner_name = EXCLUDED.summoner_name,
            summoner_level = EXCLUDED.summoner_level,
            profile_icon = EXCLUDED.profile_icon,
            riot_id_game_name = EXCLUDED.riot_id_game_name,
            riot_id_tagline = EXCLUDED.riot_id_tagline,
            time_played = EXCLUDED.time_played,
            longest_time_spent_living = EXCLUDED.longest_time_spent_living,
            total_time_spent_dead = EXCLUDED.total_time_spent_dead,
            champion_id = EXCLUDED.champion_id,
            champion_name = EXCLUDED.champion_name,
            champion_transform = EXCLUDED.champion_transform,
            champ_level = EXCLUDED.champ_level,
            champ_experience = EXCLUDED.champ_experience,
            individual_position = EXCLUDED.individual_position,
            team_position = EXCLUDED.team_position,
            lane = EXCLUDED.lane,
            role = EXCLUDED.role,
            position_assigned_by_matchmaking = EXCLUDED.position_assigned_by_matchmaking,
            selected_role_preferences = EXCLUDED.selected_role_preferences,
            win = EXCLUDED.win,
            eligible_for_progression = EXCLUDED.eligible_for_progression,
            game_ended_in_early_surrender = EXCLUDED.game_ended_in_early_surrender,
            game_ended_in_ignb_surrender = EXCLUDED.game_ended_in_ignb_surrender,
            game_ended_in_surrender = EXCLUDED.game_ended_in_surrender,
            team_early_surrendered = EXCLUDED.team_early_surrendered,
            team_ignb_surrendered = EXCLUDED.team_ignb_surrendered,
            caused_game_end_from_ignb_surrender = EXCLUDED.caused_game_end_from_ignb_surrender,
            was_premade_with_ignb_game_end_causer = EXCLUDED.was_premade_with_ignb_game_end_causer,
            was_premade_with_severe_transgressor = EXCLUDED.was_premade_with_severe_transgressor,
            was_severe_transgressor = EXCLUDED.was_severe_transgressor,
            was_afk = EXCLUDED.was_afk,
            kills = EXCLUDED.kills,
            deaths = EXCLUDED.deaths,
            assists = EXCLUDED.assists,
            killing_sprees = EXCLUDED.killing_sprees,
            largest_killing_spree = EXCLUDED.largest_killing_spree,
            largest_multi_kill = EXCLUDED.largest_multi_kill,
            double_kills = EXCLUDED.double_kills,
            triple_kills = EXCLUDED.triple_kills,
            quadra_kills = EXCLUDED.quadra_kills,
            penta_kills = EXCLUDED.penta_kills,
            unreal_kills = EXCLUDED.unreal_kills,
            first_blood_kill = EXCLUDED.first_blood_kill,
            first_blood_assist = EXCLUDED.first_blood_assist,
            gold_earned = EXCLUDED.gold_earned,
            gold_spent = EXCLUDED.gold_spent,
            items_purchased = EXCLUDED.items_purchased,
            consumables_purchased = EXCLUDED.consumables_purchased,
            item_0 = EXCLUDED.item_0,
            item_1 = EXCLUDED.item_1,
            item_2 = EXCLUDED.item_2,
            item_3 = EXCLUDED.item_3,
            item_4 = EXCLUDED.item_4,
            item_5 = EXCLUDED.item_5,
            item_6 = EXCLUDED.item_6,
            role_bound_item = EXCLUDED.role_bound_item,
            total_minions_killed = EXCLUDED.total_minions_killed,
            neutral_minions_killed = EXCLUDED.neutral_minions_killed,
            total_ally_jungle_minions_killed = EXCLUDED.total_ally_jungle_minions_killed,
            total_enemy_jungle_minions_killed = EXCLUDED.total_enemy_jungle_minions_killed,
            total_damage_dealt = EXCLUDED.total_damage_dealt,
            total_damage_dealt_to_champions = EXCLUDED.total_damage_dealt_to_champions,
            physical_damage_dealt = EXCLUDED.physical_damage_dealt,
            physical_damage_dealt_to_champions = EXCLUDED.physical_damage_dealt_to_champions,
            magic_damage_dealt = EXCLUDED.magic_damage_dealt,
            magic_damage_dealt_to_champions = EXCLUDED.magic_damage_dealt_to_champions,
            true_damage_dealt = EXCLUDED.true_damage_dealt,
            true_damage_dealt_to_champions = EXCLUDED.true_damage_dealt_to_champions,
            total_damage_taken = EXCLUDED.total_damage_taken,
            physical_damage_taken = EXCLUDED.physical_damage_taken,
            magic_damage_taken = EXCLUDED.magic_damage_taken,
            true_damage_taken = EXCLUDED.true_damage_taken,
            damage_self_mitigated = EXCLUDED.damage_self_mitigated,
            total_heal = EXCLUDED.total_heal,
            total_heals_on_teammates = EXCLUDED.total_heals_on_teammates,
            total_units_healed = EXCLUDED.total_units_healed,
            total_damage_shielded_on_teammates = EXCLUDED.total_damage_shielded_on_teammates,
            time_ccing_others = EXCLUDED.time_ccing_others,
            total_time_cc_dealt = EXCLUDED.total_time_cc_dealt,
            damage_dealt_to_buildings = EXCLUDED.damage_dealt_to_buildings,
            damage_dealt_to_turrets = EXCLUDED.damage_dealt_to_turrets,
            damage_dealt_to_objectives = EXCLUDED.damage_dealt_to_objectives,
            damage_dealt_to_epic_monsters = EXCLUDED.damage_dealt_to_epic_monsters,
            turret_kills = EXCLUDED.turret_kills,
            turret_takedowns = EXCLUDED.turret_takedowns,
            turrets_lost = EXCLUDED.turrets_lost,
            inhibitor_kills = EXCLUDED.inhibitor_kills,
            inhibitor_takedowns = EXCLUDED.inhibitor_takedowns,
            inhibitors_lost = EXCLUDED.inhibitors_lost,
            nexus_kills = EXCLUDED.nexus_kills,
            nexus_takedowns = EXCLUDED.nexus_takedowns,
            nexus_lost = EXCLUDED.nexus_lost,
            dragon_kills = EXCLUDED.dragon_kills,
            baron_kills = EXCLUDED.baron_kills,
            objectives_stolen = EXCLUDED.objectives_stolen,
            objectives_stolen_assists = EXCLUDED.objectives_stolen_assists,
            first_tower_kill = EXCLUDED.first_tower_kill,
            first_tower_assist = EXCLUDED.first_tower_assist,
            vision_score = EXCLUDED.vision_score,
            wards_placed = EXCLUDED.wards_placed,
            wards_killed = EXCLUDED.wards_killed,
            detector_wards_placed = EXCLUDED.detector_wards_placed,
            vision_wards_bought_in_game = EXCLUDED.vision_wards_bought_in_game,
            sight_wards_bought_in_game = EXCLUDED.sight_wards_bought_in_game,
            all_in_pings = EXCLUDED.all_in_pings,
            assist_me_pings = EXCLUDED.assist_me_pings,
            basic_pings = EXCLUDED.basic_pings,
            command_pings = EXCLUDED.command_pings,
            danger_pings = EXCLUDED.danger_pings,
            enemy_missing_pings = EXCLUDED.enemy_missing_pings,
            enemy_vision_pings = EXCLUDED.enemy_vision_pings,
            get_back_pings = EXCLUDED.get_back_pings,
            hold_pings = EXCLUDED.hold_pings,
            need_vision_pings = EXCLUDED.need_vision_pings,
            on_my_way_pings = EXCLUDED.on_my_way_pings,
            push_pings = EXCLUDED.push_pings,
            retreat_pings = EXCLUDED.retreat_pings,
            vision_cleared_pings = EXCLUDED.vision_cleared_pings,
            spell_1_casts = EXCLUDED.spell_1_casts,
            spell_2_casts = EXCLUDED.spell_2_casts,
            spell_3_casts = EXCLUDED.spell_3_casts,
            spell_4_casts = EXCLUDED.spell_4_casts,
            summoner_1_id = EXCLUDED.summoner_1_id,
            summoner_2_id = EXCLUDED.summoner_2_id,
            summoner_1_casts = EXCLUDED.summoner_1_casts,
            summoner_2_casts = EXCLUDED.summoner_2_casts,
            placement = EXCLUDED.placement,
            subteam_placement = EXCLUDED.subteam_placement,
            player_subteam_id = EXCLUDED.player_subteam_id,
            player_augment_1 = EXCLUDED.player_augment_1,
            player_augment_2 = EXCLUDED.player_augment_2,
            player_augment_3 = EXCLUDED.player_augment_3,
            player_augment_4 = EXCLUDED.player_augment_4,
            player_augment_5 = EXCLUDED.player_augment_5,
            player_augment_6 = EXCLUDED.player_augment_6,
            player_behavior = EXCLUDED.player_behavior,
            missions = EXCLUDED.missions,
            perks = EXCLUDED.perks,
            teams = EXCLUDED.teams,
            tournament_code = EXCLUDED.tournament_code
        """)
    rows = []
    total_rows = 0
    total_files = 0   
    BATCH_SIZE = 5000
    with engine.begin() as connection:
        for file_path in input_folder.glob("*.json"):
            total_files += 1
            with file_path.open("r", encoding="utf-8") as file:
                match = json.load(file)
                match_id = match["metadata"]["matchId"]
                game_creation_timestamp = match["info"]["gameCreation"]
                game_start_timestamp = match["info"]["gameStartTimestamp"]
                game_end_timestamp = match["info"]["gameEndTimestamp"]
                game_version = match["info"]["gameVersion"]
                teams = match["info"].get("teams")
                tournament_code = match["info"].get("tournamentCode")
                # Important!! The metadata.participants only contains PUUID strings
                participants = match["info"]["participants"]
                for participant in participants:
                    row = {
                    # Identifiers
                    "match_id": match_id,
                    "game_creation_timestamp" : game_creation_timestamp,
                    "game_start_timestamp" : game_start_timestamp,
                    "game_end_timestamp" : game_end_timestamp,
                    "game_version" : game_version,
                    "puuid": participant.get("puuid"),
                    "participant_id": participant.get("participantId"),
                    "team_id": participant.get("teamId"),
                    # Champion and position
                    "champion_id": participant.get("championId"),
                    "champion_name": participant.get("championName"),
                    "champion_transform": participant.get("championTransform"),
                    "champ_level": participant.get("champLevel"),
                    "champ_experience": participant.get("champExperience"),
        
                    "individual_position": participant.get("individualPosition"),
                    "team_position": participant.get("teamPosition"),
                    "lane": participant.get("lane"),
                    "role": participant.get("role"),
        
                    "position_assigned_by_matchmaking": participant.get("positionAssignedByMatchmaking"),
                    "selected_role_preferences": participant.get("selectedRolePreferences"),
        
                    # Match result and how it went
                    "win": participant.get("win"),
                    "eligible_for_progression": participant.get("eligibleForProgression"),
        
                    "game_ended_in_early_surrender": participant.get("gameEndedInEarlySurrender"),
                    "game_ended_in_ignb_surrender": participant.get("gameEndedInIGNBSurrender"),
                    "game_ended_in_surrender": participant.get("gameEndedInSurrender"),
        
                    "team_early_surrendered": participant.get("teamEarlySurrendered"),
                    "team_ignb_surrendered": participant.get("teamIGNBSurrendered"),
        
                    "caused_game_end_from_ignb_surrender": participant.get("causedGameEndFromIGNBSurrender" ),
                    "was_premade_with_ignb_game_end_causer": participant.get("wasPremadeWithIGNBGameEndCauser"),
                    "was_premade_with_severe_transgressor": participant.get( "wasPremadeWithSevereTransgressor"),
                    "was_severe_transgressor": participant.get("wasSevereTransgressor"),
                    "was_afk": participant.get("wasAfk"),
        
                    # KDA (kills, deaths and assist)
                    "kills": participant.get("kills"),
                    "deaths": participant.get("deaths"),
                    "assists": participant.get("assists"),
        
                    "killing_sprees": participant.get("killingSprees"),
                    "largest_killing_spree": participant.get("largestKillingSpree"),
                    "largest_multi_kill": participant.get("largestMultiKill"),
        
                    "double_kills": participant.get("doubleKills"),
                    "triple_kills": participant.get("tripleKills"),
                    "quadra_kills": participant.get("quadraKills"),
                    "penta_kills": participant.get("pentaKills"),
                    "unreal_kills": participant.get("unrealKills"),
        
                    "first_blood_kill": participant.get("firstBloodKill"),
                    "first_blood_assist": participant.get("firstBloodAssist"),
        
                    # Gold and purchases
                    "gold_earned": participant.get("goldEarned"),
                    "gold_spent": participant.get("goldSpent"),
                    "items_purchased": participant.get("itemsPurchased"),
                    "consumables_purchased": participant.get("consumablesPurchased"),
        
                    # Items
                    "item_0": participant.get("item0"),
                    "item_1": participant.get("item1"),
                    "item_2": participant.get("item2"),
                    "item_3": participant.get("item3"),
                    "item_4": participant.get("item4"),
                    "item_5": participant.get("item5"),
                    "item_6": participant.get("item6"),
                    "role_bound_item": participant.get("roleBoundItem"),
        
                    # Minions
                    "total_minions_killed": participant.get("totalMinionsKilled"),
                    "neutral_minions_killed": participant.get("neutralMinionsKilled"),
                    "total_ally_jungle_minions_killed": participant.get("totalAllyJungleMinionsKilled"),
                    "total_enemy_jungle_minions_killed": participant.get("totalEnemyJungleMinionsKilled"),
        
                    # Damage dealt
                    "total_damage_dealt": participant.get("totalDamageDealt"),
                    "total_damage_dealt_to_champions": participant.get("totalDamageDealtToChampions"),
        
                    "physical_damage_dealt": participant.get("physicalDamageDealt"),
                    "physical_damage_dealt_to_champions": participant.get("physicalDamageDealtToChampions"),
        
                    "magic_damage_dealt": participant.get("magicDamageDealt"),
                    "magic_damage_dealt_to_champions": participant.get("magicDamageDealtToChampions"),
            
                    "true_damage_dealt": participant.get("trueDamageDealt"),
                    "true_damage_dealt_to_champions": participant.get("trueDamageDealtToChampions"),
        
                    # Damage taken and mitigated
                    "total_damage_taken": participant.get("totalDamageTaken"),
                    "physical_damage_taken": participant.get("physicalDamageTaken"),
                    "magic_damage_taken": participant.get("magicDamageTaken"),
                    "true_damage_taken": participant.get("trueDamageTaken"),
                    "damage_self_mitigated": participant.get("damageSelfMitigated"),
        
                    # Healing and shield
                    "total_heal": participant.get("totalHeal"),
                    "total_heals_on_teammates": participant.get("totalHealsOnTeammates"),
                    "total_units_healed": participant.get("totalUnitsHealed"),
                    "total_damage_shielded_on_teammates": participant.get("totalDamageShieldedOnTeammates"),
            
                    # Crowd control
                    "time_ccing_others": participant.get("timeCCingOthers"),
                    "total_time_cc_dealt": participant.get("totalTimeCCDealt"),
        
                    # Objectives and structures
                    "damage_dealt_to_buildings": participant.get("damageDealtToBuildings"),
                    "damage_dealt_to_turrets": participant.get("damageDealtToTurrets"),
                    "damage_dealt_to_objectives": participant.get("damageDealtToObjectives"),
                    "damage_dealt_to_epic_monsters": participant.get("damageDealtToEpicMonsters"),
        
                    "turret_kills": participant.get("turretKills"),
                    "turret_takedowns": participant.get("turretTakedowns"),
                    "turrets_lost": participant.get("turretsLost"),
        
                    "inhibitor_kills": participant.get("inhibitorKills"),
                    "inhibitor_takedowns": participant.get("inhibitorTakedowns"),
                    "inhibitors_lost": participant.get("inhibitorsLost"),
        
                    "nexus_kills": participant.get("nexusKills"),
                    "nexus_takedowns": participant.get("nexusTakedowns"),
                    "nexus_lost": participant.get("nexusLost"),
        
                    "dragon_kills": participant.get("dragonKills"),
                    "baron_kills": participant.get("baronKills"),
        
                     "objectives_stolen": participant.get("objectivesStolen"),
                    "objectives_stolen_assists": participant.get( "objectivesStolenAssists"),
            
                    "first_tower_kill": participant.get("firstTowerKill"),
                    "first_tower_assist": participant.get("firstTowerAssist"),
            
                    # Vision
                    "vision_score": participant.get("visionScore"),
                    "wards_placed": participant.get("wardsPlaced"),
                    "wards_killed": participant.get("wardsKilled"),
                    "detector_wards_placed": participant.get("detectorWardsPlaced"),
                    "vision_wards_bought_in_game": participant.get("visionWardsBoughtInGame" ),
                    "sight_wards_bought_in_game": participant.get( "sightWardsBoughtInGame"),
        
                    # Pings
                    "all_in_pings": participant.get("allInPings"),
                    "assist_me_pings": participant.get("assistMePings"),
                    "basic_pings": participant.get("basicPings"),
                    "command_pings": participant.get("commandPings"),
                    "danger_pings": participant.get("dangerPings"),
                    "enemy_missing_pings": participant.get("enemyMissingPings"),
                    "enemy_vision_pings": participant.get("enemyVisionPings"),
                    "get_back_pings": participant.get("getBackPings"),
                    "hold_pings": participant.get("holdPings"),
                    "need_vision_pings": participant.get("needVisionPings"),
                    "on_my_way_pings": participant.get("onMyWayPings"),
                    "push_pings": participant.get("pushPings"),
                    "retreat_pings": participant.get("retreatPings"),
                    "vision_cleared_pings": participant.get("visionClearedPings"),
        
                    # Champion spell casts
                    "spell_1_casts": participant.get("spell1Casts"),
                    "spell_2_casts": participant.get("spell2Casts"),
                    "spell_3_casts": participant.get("spell3Casts"),
                    "spell_4_casts": participant.get("spell4Casts"),
        
                    # Summoner spells
                    "summoner_1_id": participant.get("summoner1Id"),
                    "summoner_2_id": participant.get("summoner2Id"),
                    "summoner_1_casts": participant.get("summoner1Casts"),
                    "summoner_2_casts": participant.get("summoner2Casts"),
        
                    # Summoner information
                    "summoner_id": participant.get("summonerId"),
                    "summoner_name": participant.get("summonerName"),
                    "summoner_level": participant.get("summonerLevel"),
                    "profile_icon": participant.get("profileIcon"),
                    "riot_id_game_name": participant.get("riotIdGameName"),
                    "riot_id_tagline": participant.get("riotIdTagline"),
        
                    # Time
                    "time_played": participant.get("timePlayed"),
                     "longest_time_spent_living": participant.get( "longestTimeSpentLiving" ),
                    "total_time_spent_dead": participant.get("totalTimeSpentDead"),
        
                     # Arena and other mode fields (this should not be relevant since I'm only choosing the solo queue)
                    "placement": participant.get("placement"),
                    "subteam_placement": participant.get("subteamPlacement"),
                    "player_subteam_id": participant.get("playerSubteamId"),
            
                    "player_augment_1": participant.get("playerAugment1"),
                    "player_augment_2": participant.get("playerAugment2"),
                    "player_augment_3": participant.get("playerAugment3"),
                    "player_augment_4": participant.get("playerAugment4"),
                    "player_augment_5": participant.get("playerAugment5"),
                    "player_augment_6": participant.get("playerAugment6"),
            
                    # Nested elements kept raw (I am keeping them in Bronze)
                    "player_behavior": json.dumps(participant.get("PlayerBehavior")),
                    "missions": json.dumps(participant.get("missions")),
                    "perks": json.dumps(participant.get("perks")),
                    "teams": json.dumps(teams),
                    "tournament_code": tournament_code,
                    }   
                    rows.append(row)
                    total_rows += 1

                    #This is bc the data size is very big and is better to control it through batches
                    if len(rows) >= BATCH_SIZE:
                        connection.execute(insert_query, rows)
                        rows.clear()

            # I could have kept only the data for the players in the sample
            # list, but since this is Bronze I believe it is not correct to
            # erase those (I don't know what I might want them for later on)
               
            #CHECKPOINT
            if total_files % 1000 == 0:
                print(f"Processed {total_files} match files {total_rows} participant rows...")
 
                
        # This inserts anything left after the final batch just in case there is something missing
        if rows:
            connection.execute(insert_query, rows)
    print(f"Loaded {total_rows} participant rows from {total_files} match files into PostgreSQL")
