CREATE TABLE IF NOT EXISTS champions_silver (
    --champion info
    champion_id INTEGER NOT NULL,
    --Im deleting code bc it contains the same info as name but without the spaces and is erdundant
    name VARCHAR(100) NOT NULL,

    --characteristic
    primary_tag VARCHAR(50) NOT NULL,
    secondary_tag VARCHAR(50),
    partype VARCHAR(50),
    difficulty SMALLINT,

    -- general stats 
    attack SMALLINT,
    defense SMALLINT,
    magic SMALLINT,
    
    -- stats desglosadas
    hp REAL,
    hp_per_level REAL,
    mp REAL,
    mp_per_level REAL,
    move_speed REAL,
    armor REAL,
    armor_per_level REAL,
    spell_block REAL,
    spell_block_per_level REAL,
    attack_range REAL,
    hp_regen REAL,
    hp_regen_per_level REAL,
    mp_regen REAL,
    mp_regen_per_level REAL,
    crit REAL,
    crit_per_level REAL,
    attack_damage REAL,
    attack_damage_per_level REAL,
    attack_speed_per_level REAL,
    attack_speed REAL,
    --ddragon version
    ddragon_version VARCHAR(20) NOT NULL,
    --IMPORTANT PRIMARY KEY
    PRIMARY KEY (champion_id, ddragon_version)
);

INSERT INTO champions_silver (
    champion_id ,
    name ,
    primary_tag ,
    secondary_tag ,
    partype,
    difficulty ,
    attack ,
    defense ,
    magic ,
    hp ,
    hp_per_level ,
    mp ,
    mp_per_level ,
    move_speed ,
    armor ,
    armor_per_level ,
    spell_block ,
    spell_block_per_level ,
    attack_range ,
    hp_regen ,
    hp_regen_per_level ,
    mp_regen ,
    mp_regen_per_level ,
    crit ,
    crit_per_level ,
    attack_damage ,
    attack_damage_per_level ,
    attack_speed_per_level ,
    attack_speed ,
    ddragon_version )
SELECT 
    champb.champion_id ,
    champb.name ,
    champb.primary_tag ,
    champb.secondary_tag ,
    champb.partype,
    champb.difficulty ,
    champb.attack ,
    champb.defense ,
    champb.magic ,
    champb.hp ,
    champb.hp_per_level ,
    champb.mp ,
    champb.mp_per_level ,
    champb.move_speed ,
    champb.armor ,
    champb.armor_per_level ,
    champb.spell_block ,
    champb.spell_block_per_level ,
    champb.attack_range ,
    champb.hp_regen ,
    champb.hp_regen_per_level ,
    champb.mp_regen ,
    champb.mp_regen_per_level ,
    champb.crit ,
    champb.crit_per_level ,
    champb.attack_damage ,
    champb.attack_damage_per_level ,
    champb.attack_speed_per_level ,
    champb.attack_speed ,
    champb.ddragon_version
FROM champions_bronze AS champb
ON CONFLICT (champion_id, ddragon_version)
DO UPDATE SET
    name =  EXCLUDED.name ,
    primary_tag =  EXCLUDED.primary_tag ,
    secondary_tag =  EXCLUDED.secondary_tag,
    partype=  EXCLUDED.partype ,
    difficulty =  EXCLUDED.difficulty ,
    attack =  EXCLUDED.attack ,
    defense =  EXCLUDED.defense ,
    magic =  EXCLUDED.magic ,
    hp =  EXCLUDED.hp ,
    hp_per_level=  EXCLUDED.hp_per_level ,
    mp =  EXCLUDED.mp ,
    mp_per_level =  EXCLUDED.mp_per_level ,
    move_speed =  EXCLUDED.move_speed ,
    armor =  EXCLUDED.armor ,
    armor_per_level =  EXCLUDED.armor_per_level ,
    spell_block =  EXCLUDED.spell_block ,
    spell_block_per_level =  EXCLUDED.spell_block_per_level ,
    attack_range =  EXCLUDED.attack_range ,
    hp_regen =  EXCLUDED.hp_regen ,
    hp_regen_per_level =  EXCLUDED.hp_regen_per_level ,
    mp_regen =  EXCLUDED.mp_regen ,
    mp_regen_per_level =  EXCLUDED.mp_regen_per_level ,
    crit =  EXCLUDED.crit ,
    crit_per_level =  EXCLUDED.crit_per_level ,
    attack_damage=  EXCLUDED.attack_damage  ,
    attack_damage_per_level =  EXCLUDED.attack_damage_per_level ,
    attack_speed_per_level=  EXCLUDED.attack_speed_per_level  ,
    attack_speed=  EXCLUDED.attack_speed  
;
